// Code generated by stanc 4d256d1
#include <stan/model/model_header.hpp>
namespace model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 7> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 10, column 13 to column 24)",
  " (in 'string', line 11, column 8 to column 29)",
  " (in 'string', line 4, column 4 to column 13)",
  " (in 'string', line 3, column 24 to line 5, column 3)",
  " (in 'string', line 7, column 4 to column 17)",
  " (in 'string', line 6, column 32 to line 8, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>>* = nullptr>
stan::return_type_t<T0__> overload(const T0__& a, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>* = nullptr>
stan::return_type_t<T0__, T1__>
overload(const T0__& a, const T1__& b, std::ostream* pstream__);
// real overload(real)
template <typename T0__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>>*>
stan::return_type_t<T0__> overload(const T0__& a, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 3;
    return a;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real overload(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>*>
stan::return_type_t<T0__, T1__>
overload(const T0__& a, const T1__& b, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 5;
    return (a + b);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
}
// [[stan::function]]
double overload(const double& a, std::ostream* pstream__ = nullptr) {
  return model_namespace::overload(a, pstream__);
}
// [[stan::function]]
double
overload(const double& a, const double& b, std::ostream* pstream__ = nullptr) {
  return model_namespace::overload(a, b, pstream__);
}
