// Code generated by stanc 4d256d1
#include <stan/model/model_header.hpp>
namespace model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 9> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 13, column 13 to column 24)",
  " (in 'string', line 14, column 8 to column 29)",
  " (in 'string', line 4, column 4 to column 17)",
  " (in 'string', line 3, column 30 to line 5, column 3)",
  " (in 'string', line 7, column 4 to column 36)",
  " (in 'string', line 6, column 34 to line 8, column 3)",
  " (in 'string', line 10, column 4 to column 19)",
  " (in 'string', line 9, column 19 to line 11, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>* = nullptr>
stan::return_type_t<T0__, T1__>
my_add(const T0__& a, const T1__& b, std::ostream* pstream__);
template <typename T0__, typename T1__, typename RNG,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>* = nullptr>
stan::return_type_t<T0__, T1__>
my_add_rng(const T0__& a, const T1__& b, RNG& base_rng__, std::ostream*
           pstream__);
void say_hello(std::ostream* pstream__);
// real my_add(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>*>
stan::return_type_t<T0__, T1__>
my_add(const T0__& a, const T1__& b, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 3;
    return (a + b);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real my_add_rng(real, real)
template <typename T0__, typename T1__, typename RNG,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>>*>
stan::return_type_t<T0__, T1__>
my_add_rng(const T0__& a, const T1__& b, RNG& base_rng__, std::ostream*
           pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 5;
    return ((a + b) + stan::math::normal_rng(0, 1, base_rng__));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// void say_hello()
void say_hello(std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 7;
    if (pstream__) {
      stan::math::stan_print(pstream__, "hello");
      *(pstream__) << std::endl;
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
}
// [[stan::function]]
double
my_add(const double& a, const double& b, std::ostream* pstream__ = nullptr) {
  return model_namespace::my_add(a, b, pstream__);
}
// [[stan::function]]
double
my_add_rng(const double& a, const double& b, stan::rng_t& base_rng__,
           std::ostream* pstream__ = nullptr) {
  return model_namespace::my_add_rng(a, b, base_rng__, pstream__);
}
// [[stan::function]]
void say_hello(std::ostream* pstream__ = nullptr) {
  model_namespace::say_hello(pstream__);
}
