// Code generated by stanc 4d256d1
#include <stan/model/model_header.hpp>
namespace model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 5> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 7, column 13 to column 24)",
  " (in 'string', line 8, column 8 to column 29)",
  " (in 'string', line 4, column 4 to column 22)",
  " (in 'string', line 3, column 39 to line 5, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>>* = nullptr>
std::tuple<stan::return_type_t<T0__>, stan::return_type_t<T0__>>
two_things(const T0__& a, std::ostream* pstream__);
// tuple(real, real) two_things(real)
template <typename T0__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff_scalar<T0__>,
                                stan::is_floating_point<T0__>>>*>
std::tuple<stan::return_type_t<T0__>, stan::return_type_t<T0__>>
two_things(const T0__& a, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<T0__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 3;
    return std::forward_as_tuple(a, (a + 1));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
}
// [[stan::function]]
std::tuple<double, double>
two_things(const double& a, std::ostream* pstream__ = nullptr) {
  return model_namespace::two_things(a, pstream__);
}
