// Code generated by stanc 4d256d1
#include <stan/model/model_header.hpp>
namespace model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 9> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 13, column 13 to column 24)",
  " (in 'string', line 14, column 8 to column 29)",
  " (in 'string', line 4, column 4 to column 13)",
  " (in 'string', line 3, column 46 to line 5, column 3)",
  " (in 'string', line 7, column 4 to column 13)",
  " (in 'string', line 6, column 34 to line 8, column 3)",
  " (in 'string', line 10, column 4 to column 13)",
  " (in 'string', line 9, column 43 to line 11, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              stan::math::disjunction<stan::is_autodiff_scalar<
                                                        stan::value_type_t<T0__>>,
                                stan::is_floating_point<stan::value_type_t<T0__>>>,
                              stan::is_integral<T1__>>* = nullptr>
std::vector<stan::return_type_t<stan::base_type_t<T0__>>>
arr_fun(const T0__& x, const T1__& n, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,1,-1>
rv_fun(const T0__& x_arg__, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              stan::is_std_vector<stan::value_type_t<T0__>>,
                              stan::is_integral<stan::value_type_t<stan::value_type_t<T0__>>>>* = nullptr>
std::vector<std::vector<int>>
int_arr_fun(const T0__& x, std::ostream* pstream__);
// array[] real arr_fun(array[] real, int)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              stan::math::disjunction<stan::is_autodiff_scalar<
                                                        stan::value_type_t<T0__>>,
                                stan::is_floating_point<stan::value_type_t<T0__>>>,
                              stan::is_integral<T1__>>*>
std::vector<stan::return_type_t<stan::base_type_t<T0__>>>
arr_fun(const T0__& x, const T1__& n, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 3;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// row_vector rv_fun(row_vector)
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,1,-1>
rv_fun(const T0__& x_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 5;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// array[,] int int_arr_fun(array[,] int)
template <typename T0__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              stan::is_std_vector<stan::value_type_t<T0__>>,
                              stan::is_integral<stan::value_type_t<stan::value_type_t<T0__>>>>*>
std::vector<std::vector<int>>
int_arr_fun(const T0__& x, std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 7;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
}
// [[stan::function]]
std::vector<double>
arr_fun(const std::vector<double>& x, const int& n, std::ostream*
        pstream__ = nullptr) {
  return model_namespace::arr_fun(x, n, pstream__);
}
// [[stan::function]]
Eigen::Matrix<double,1,-1>
rv_fun(const Eigen::Matrix<double,1,-1>& x, std::ostream* pstream__ = nullptr) {
  return model_namespace::rv_fun(x, pstream__);
}
// [[stan::function]]
std::vector<std::vector<int>>
int_arr_fun(const std::vector<std::vector<int>>& x, std::ostream*
            pstream__ = nullptr) {
  return model_namespace::int_arr_fun(x, pstream__);
}
