// Code generated by stanc 4d256d1
#include <stan/model/model_header.hpp>
namespace model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 7> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 10, column 13 to column 24)",
  " (in 'string', line 11, column 8 to column 29)",
  " (in 'string', line 4, column 4 to column 17)",
  " (in 'string', line 3, column 37 to line 5, column 3)",
  " (in 'string', line 7, column 4 to column 17)",
  " (in 'string', line 6, column 38 to line 8, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,1>
vec_add(const T0__& a_arg__, const T1__& b_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,-1>
mat_mult(const T0__& a_arg__, const T1__& b_arg__, std::ostream* pstream__);
// vector vec_add(vector, vector)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,1>
vec_add(const T0__& a_arg__, const T1__& b_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& a = stan::math::to_ref(a_arg__);
  const auto& b = stan::math::to_ref(b_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 3;
    return stan::math::add(a, b);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// matrix mat_mult(matrix, matrix)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>>,-1,-1>
mat_mult(const T0__& a_arg__, const T1__& b_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& a = stan::math::to_ref(a_arg__);
  const auto& b = stan::math::to_ref(b_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 5;
    return stan::math::multiply(a, b);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
}
// [[stan::function]]
Eigen::Matrix<double,-1,1>
vec_add(const Eigen::Matrix<double,-1,1>& a,
        const Eigen::Matrix<double,-1,1>& b, std::ostream*
        pstream__ = nullptr) {
  return model_namespace::vec_add(a, b, pstream__);
}
// [[stan::function]]
Eigen::Matrix<double,-1,-1>
mat_mult(const Eigen::Matrix<double,-1,-1>& a,
         const Eigen::Matrix<double,-1,-1>& b, std::ostream*
         pstream__ = nullptr) {
  return model_namespace::mat_mult(a, b, pstream__);
}
