// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {
namespace dens {

STANLI_DEFINE_DENSITY_FWD(OP_SCALED_INV_CHI_SQUARE_LPDF, scaled_inv_chi_square_lpdf, 3, 2)

}  // namespace dens
}  // namespace stanli
