// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {
namespace dens {

STANLI_DEFINE_DENSITY_FWD(OP_EXP_MOD_NORMAL_LPDF, exp_mod_normal_lpdf, 4, 2)

}  // namespace dens
}  // namespace stanli
