// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {
namespace dens {

STANLI_DEFINE_DENSITY_FWD(OP_CAUCHY_LPDF, cauchy_lpdf, 3, 3)

}  // namespace dens
}  // namespace stanli
