#!/bin/sh
# Vendors stanli (github.com/seantalts/stanli), following this package's
# convention for bundled libraries
set -e

STANLI_REF="2f56496"
STANLI_TARBALL="stanli-$STANLI_REF.tar.gz"
STANLI_URL="https://github.com/seantalts/stanli/archive/$STANLI_REF.tar.gz"

if [ ! -f "$STANLI_TARBALL" ]; then
  curl -sSL -o "$STANLI_TARBALL" "$STANLI_URL"
fi
tar -xf "$STANLI_TARBALL"
STANLI_DIR=$(find . -maxdepth 1 -type d -name 'stanli-*')

SRC=../src/stanli

rm -rf "$SRC"
mkdir -p "$SRC/runtime"

cp -f "$STANLI_DIR/LICENSE" "$SRC/"

cp -Rf "$STANLI_DIR/runtime/include" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/src" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/kernels" "$SRC/runtime/"
rm -f "$SRC/runtime/include/stanli/README.md"

rm -f "$SRC/runtime/src/capi.cpp" \
      "$SRC/runtime/src/bridgestan_abi.cpp" \
      "$SRC/runtime/src/stanc_embed_c.cpp" \
      "$SRC/runtime/src/nuts.cpp" \
      "$SRC/runtime/src/estimate.cpp" \
      "$SRC/runtime/src/diagnose.cpp" \
      "$SRC/runtime/src/walnuts.cpp" \
      "$SRC/runtime/src/data.cpp" \
      "$SRC/runtime/src/README.md" \
      "$SRC/runtime/src/OPTIMIZATIONS.md"
rm -f "$SRC/runtime/include/stanli/capi.h" \
      "$SRC/runtime/include/stanli/bridgestan_internal.hpp" \
      "$SRC/runtime/include/stanli/nuts.hpp" \
      "$SRC/runtime/include/stanli/estimate.hpp" \
      "$SRC/runtime/include/stanli/diagnose.hpp" \
      "$SRC/runtime/include/stanli/walnuts.hpp" \
      "$SRC/runtime/include/stanli/model_adapter.hpp"

python3 - "$SRC/runtime/include/stanli/optable.hpp" "$SRC/runtime/kernels" << 'EOF'
import glob
import os
import re
import sys

optable_path, kernels_dir = sys.argv[1], sys.argv[2]
text = open(optable_path).read()

def macro_body(name):
    # Everything after "#define NAME(X)" up to (and including) the first
    # line whose newline isn't escaped by a line-continuation backslash.
    m = re.search(r'#define\s+' + re.escape(name) + r'\(X\)(.*?)(?<!\\)\n',
                  text, re.S)
    assert m, f"{name}(X) not found -- optable.hpp changed upstream"
    return m.group(1)

# Discover the list's membership from STANLI_SCALAR_DENSITY_LIST(X)
# itself rather than naming its sub-lists, so a future reshuffle of the
# grouping upstream doesn't silently drop or duplicate a distribution.
sub_lists = re.findall(r'(STANLI_SCALAR_DENSITY_LIST_\w+)\(X\)',
                        macro_body("STANLI_SCALAR_DENSITY_LIST"))
assert sub_lists, ("no sub-lists in STANLI_SCALAR_DENSITY_LIST(X) -- "
                    "optable.hpp changed upstream")

entry_re = re.compile(
    r'X\(\s*([A-Z0-9_]+)\s*,\s*([a-z0-9_]+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)')
entries = []  # (code, fn, nargs, tier)
for sub in sub_lists:
    found = entry_re.findall(macro_body(sub))
    assert found, f"{sub}(X) has no entries -- optable.hpp changed upstream"
    entries.extend(found)

names = [fn for _, fn, _, _ in entries]
assert len(names) == len(set(names)), "a density name appears in two sub-lists"

# The files currently defining these entries are whatever kernels/*.cpp
# instantiate a density sub-list -- not a fixed filename list, since
# upstream is free to rename or regroup its shards.
shard_call_re = re.compile(
    r'STANLI_SCALAR_DENSITY_LIST_\w+\(STANLI_DEFINE_DENSITY_FWD\)')
old_shards = [p for p in glob.glob(os.path.join(kernels_dir, "*.cpp"))
              if shard_call_re.search(open(p).read())]
assert old_shards, ("no existing density shard files found -- "
                     "kernels/ layout changed upstream")
for p in old_shards:
    os.remove(p)

template = """// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {{
namespace dens {{

STANLI_DEFINE_DENSITY_FWD({code}, {fn}, {nargs}, {tier})

}}  // namespace dens
}}  // namespace stanli
"""
for code, fn, nargs, tier in entries:
    out_path = os.path.join(kernels_dir, f"densities_{fn}.cpp")
    assert not os.path.exists(out_path), f"{out_path} already exists"
    open(out_path, "w").write(
        template.format(code=code, fn=fn, nargs=nargs, tier=tier))
EOF

# stanli::DataMap::set_int_array() only ever built a 1-D entry
python3 - "$SRC/runtime/include/stanli/data.hpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_sig = "  void set_int_array(const std::string& name, std::vector<int> v) {\n"
new_sig = (
    "  void set_int_array(const std::string& name, std::vector<int> v,\n"
    "                     std::vector<int64_t> dims = {}) {\n"
)
assert old_sig in text, "set_int_array signature not found -- data.hpp changed upstream"
text = text.replace(old_sig, new_sig, 1)

old_dims = "    e.dims = {static_cast<int64_t>(v.size())};\n"
new_dims = (
    "    e.dims = dims.empty() ? std::vector<int64_t>{static_cast<int64_t>(v.size())}\n"
    "                          : std::move(dims);\n"
)
assert old_dims in text, "set_int_array dims assignment not found -- data.hpp changed upstream"
text = text.replace(old_dims, new_dims, 1)

old_from_json = (
    "  // Each factory lives in its own translation unit -- data.cpp for the JSON\n"
    "  // pair, data_var_context.cpp for this one -- so a build can drop either.\n"
    "  static DataMap from_json_file(const std::string& path);\n"
    "  static DataMap from_json(const std::string& text);\n"
    "  static DataMap from_var_context(const stan::io::var_context& context);\n"
)
new_from_json = (
    "  // data.cpp (the JSON factory pair) is dropped during vendoring -- it\n"
    "  // pulls in nlohmann_json, which isn't vendored -- leaving this as the\n"
    "  // only factory built.\n"
    "  static DataMap from_var_context(const stan::io::var_context& context);\n"
)
assert old_from_json in text, "from_json/from_var_context declarations not found -- data.hpp changed upstream"
text = text.replace(old_from_json, new_from_json, 1)

open(path, "w").write(text)
EOF

# R CMD check flags raw stdio in compiled code (calls that write to
# stdout/stderr instead of R's console, or that use unbounded formatting).
# None of what follows is reachable through stanr: the STANLI_DEBUG_*
# traces are gated behind env vars stanr never sets, and profile_report()
# is never called -- so these are patched out/around rather than left to
# trip the check.

# print()/reject() with no sink installed fell back to raw stdout. stanr
# does not install a sink (chains run across TBB worker threads, where
# calling back into R's console API would not be safe), so drop the
# message instead of writing around R's console.
python3 - "$SRC/runtime/src/message_sink.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- message_sink.cpp changed upstream"
text = text.replace(old_include, "", 1)

old_body = """  if (sink()) {
    sink()(text.data(), text.size());
    return;
  }
  // The default, and what both paths did before there was a sink: the
  // line and its newline to stdout. One fwrite per call rather than two,
  // so a line cannot be split by another thread's output.
  std::string line = text;
  line += '\\n';
  std::fwrite(line.data(), 1, line.size(), stdout);
}
"""
new_body = """  if (sink()) sink()(text.data(), text.size());
  // No sink installed: stanr does not call set_message_sink() (yet), and
  // the default fallback wrote to the process's raw stdout, which R CMD
  // check flags. Drop the message rather than write around R's console.
}
"""
assert old_body in text, "emit_message body not found -- message_sink.cpp changed upstream"
text = text.replace(old_body, new_body, 1)

# This TU's local sink() clashes with the unrelated struct stanli::sink
# (recorder.hpp) once src/Makevars's PCH forces recorder.hpp into every
# stanli translation unit -- ambiguous lookup, not visible when this file
# is compiled standalone. Rename the local one out of the way.
old_decl = "MessageSink& sink() {\n"
new_decl = "MessageSink& current_sink() {\n"
assert old_decl in text, "sink() declaration not found -- message_sink.cpp changed upstream"
text = text.replace(old_decl, new_decl, 1)

old_set = "  sink() = std::move(s);\n"
new_set = "  current_sink() = std::move(s);\n"
assert old_set in text, "set_message_sink() body not found -- message_sink.cpp changed upstream"
text = text.replace(old_set, new_set, 1)

old_emit = "  if (sink()) sink()(text.data(), text.size());\n"
new_emit = "  if (current_sink()) current_sink()(text.data(), text.size());\n"
assert old_emit in text, "emit_message() sink call not found -- message_sink.cpp changed upstream"
text = text.replace(old_emit, new_emit, 1)

open(path, "w").write(text)
EOF

# STANLI_DEBUG_ISLAND traces to stderr; stanr never sets it.
python3 - "$SRC/runtime/src/island.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_no_adjoint = """      // A refusal is not an error -- the replay still gives the right
      // gradient -- but it is worth being able to see, because it is the
      // difference between a region that is fast and one that merely
      // works, and nothing else about the model would show it.
      if (!gen && std::getenv("STANLI_DEBUG_ISLAND"))
        std::fprintf(stderr,
                     "island: no adjoint generated for a %zu-op region; "
                     "it will replay under var\\n",
                     j - i);
    }
"""
new_no_adjoint = """    }
"""
assert old_no_adjoint in text, "no-adjoint debug trace not found -- island.cpp changed upstream"
text = text.replace(old_no_adjoint, new_no_adjoint, 1)

old_cost = """      if (std::getenv("STANLI_DEBUG_ISLAND"))
        std::fprintf(stderr, "island? ops=%zu graph=%lld island=%lld\\n", j - i,
                     (long long)graph_cost, (long long)island_cost);
      if (graph_cost < island_cost) compiled = false;
"""
new_cost = """      if (graph_cost < island_cost) compiled = false;
"""
assert old_cost in text, "island-cost debug trace not found -- island.cpp changed upstream"
text = text.replace(old_cost, new_cost, 1)

old_carved = """        if (std::getenv("STANLI_DEBUG_ISLAND")) {
          const IslandProg& p = *static_cast<const IslandProg*>(is.udata);
          std::fprintf(stderr,
                       "island: ops=%zu instr=%zu regs=%d ins=%zu outs=%zu "
                       "adj=%zu\\n",
                       j - i, p.code.size(), p.n_regs, p.ins.size(),
                       p.out_regs.size(), p.adj.code.size());
          // Which instructions the region is made of, so a disagreement
          // with the replay can be attributed to an opcode rather than
          // guessed at.
          std::vector<int> hist(64, 0);
          for (const auto& I : p.code)
            if ((int)I.code < 64) ++hist[(size_t)I.code];
          std::fprintf(stderr, "island opcodes:");
          for (int c = 0; c < 64; ++c)
            if (hist[(size_t)c])
              std::fprintf(stderr, " %d:%d", c, hist[(size_t)c]);
          std::fprintf(stderr, "\\n");
        }
        ++carved;
"""
new_carved = """        ++carved;
"""
assert old_carved in text, "carved-island debug trace not found -- island.cpp changed upstream"
text = text.replace(old_carved, new_carved, 1)

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- island.cpp changed upstream"
text = text.replace(old_include, "", 1)

open(path, "w").write(text)
EOF

# STANLI_DEBUG_ODE traces to stderr; stanr never sets it.
python3 - "$SRC/runtime/src/lower.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_doc = """  // The op tail both ODE families share: report an interpreter fallback,
  // emit OP_ODE and hand the spec to the graph.
"""
new_doc = """  // The op tail both ODE families share: emit OP_ODE and hand the spec
  // to the graph.
"""
assert old_doc in text, "emit_ode doc comment not found -- lower.cpp changed upstream"
text = text.replace(old_doc, new_doc, 1)

old_trace = """    // Falling back to the interpreter is correct but ~30x slower, so make
    // it findable rather than silent.
    if (!spec->prog.ok && std::getenv("STANLI_DEBUG_ODE"))
      std::fprintf(stderr,
                   "stanli: ODE right-hand side %s falls back to the "
                   "interpreter: %s\\n",
                   spec->rhs_name.c_str(), spec->prog.why.c_str());
    Val v = emit_value(OP_ODE, {z0, theta}, N * S, result_si, {(int)N, (int)S});
"""
new_trace = """    Val v = emit_value(OP_ODE, {z0, theta}, N * S, result_si, {(int)N, (int)S});
"""
assert old_trace in text, "ODE fallback debug trace not found -- lower.cpp changed upstream"
text = text.replace(old_trace, new_trace, 1)

old_include = "#include <cstdio>\n"
assert old_include in text, "cstdio include not found -- lower.cpp changed upstream"
text = text.replace(old_include, "", 1)

open(path, "w").write(text)
EOF

# R CMD check flags assert() in compiled code (it lowers to abort() via
# ___assert_rtn), and PKG_CPPFLAGS doesn't define NDEBUG for this build, so
# these stay live in the shipped binary. Each one guards an invariant the
# carver/type-checker already guarantees by construction (registered
# opcodes, scalar-length operands), so drop them rather than ship a check
# that can't actually fail.
python3 - "$SRC/runtime/kernels/elementwise.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_include = "#include <cassert>\n"
assert old_include in text, "cassert include not found -- elementwise.cpp changed upstream"
text = text.replace(old_include, "", 1)

old_check = "    assert(ctx.in[i].len == 1);\n    acc += ctx.in[i].data[0];\n"
new_check = "    acc += ctx.in[i].data[0];\n"
assert old_check in text, "add_n_fwd length assert not found -- elementwise.cpp changed upstream"
text = text.replace(old_check, new_check, 1)

open(path, "w").write(text)
EOF

python3 - "$SRC/runtime/src/executor.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_include = "#include <cassert>\n"
assert old_include in text, "cassert include not found -- executor.cpp changed upstream"
text = text.replace(old_include, "", 1)

old_kernel = "  assert(opcode < OP_COUNT_);\n  return g_table[opcode];\n"
new_kernel = "  return g_table[opcode];\n"
assert old_kernel in text, "kernel() opcode assert not found -- executor.cpp changed upstream"
text = text.replace(old_kernel, new_kernel, 1)

old_register = "  assert(opcode < OP_COUNT_);\n  g_table[opcode] = k;\n"
new_register = "  g_table[opcode] = k;\n"
assert old_register in text, "register_kernel() opcode assert not found -- executor.cpp changed upstream"
text = text.replace(old_register, new_register, 1)

old_call = (
    "  assert(k != nullptr);  // the carver only emits registered opcodes\n"
    "  k->forward(ctx);\n"
)
new_call = "  k->forward(ctx);  // the carver only emits registered opcodes\n"
assert old_call in text, "run_call() null-kernel assert not found -- executor.cpp changed upstream"
text = text.replace(old_call, new_call, 1)

old_result = "  assert(r.len == 1);\n  return values_[r.offset];\n"
new_result = "  return values_[r.offset];\n"
assert old_result in text, "forward() result-length assert not found -- executor.cpp changed upstream"
text = text.replace(old_result, new_result, 1)

open(path, "w").write(text)
EOF

# run_adjoint()'s per-instruction switch has no default (deliberate: it's
# meant to catch newly added opcodes going unhandled), but CALL is already
# handled above via an `if`/`continue` before the switch, so the compiler
# still flags it as an unhandled enumerator. Add it as an explicit
# unreachable case, same as the existing JZ/JMP entries.
python3 - "$SRC/runtime/src/adjoint.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old = "    const double t = adj[I.dst];\n    switch (I.code) {\n      case Program::CONST:\n"
new = (
    "    const double t = adj[I.dst];\n"
    "    switch (I.code) {\n"
    "      case Program::CALL:\n"
    "        break;  // handled above with `continue`; unreachable here\n"
    "      case Program::CONST:\n"
)
assert old in text, "run_adjoint() switch head not found -- adjoint.cpp changed upstream"
text = text.replace(old, new, 1)

open(path, "w").write(text)
EOF

# profile_report() is never called by stanr; rewrite it over
# <sstream>/<iomanip> instead of snprintf so nothing calls it either way.
python3 - "$SRC/runtime/src/executor.cpp" << 'EOF'
import sys

path = sys.argv[1]
text = open(path).read()

old_include = "#include <cstdio>\n"
new_include = "#include <iomanip>\n#include <sstream>\n"
assert old_include in text, "cstdio include not found -- executor.cpp changed upstream"
text = text.replace(old_include, new_include, 1)

old_report = """  char line[160];
  std::string out;
  std::snprintf(line, sizeof line, "%-22s %10s %12s %12s %6s %12s\\n", "opcode",
                "calls", "fwd ns", "bwd ns", "%", "elems");
  out += line;
  for (uint16_t op : order) {
    const ProfEntry& e = prof_[op];
    std::snprintf(line, sizeof line,
                  "%-22s %10lld %12lld %12lld %5.1f%% %12lld\\n",
                  opcode_name(op), (long long)e.calls, (long long)e.fwd_ns,
                  (long long)e.bwd_ns,
                  100.0 * (double)(e.fwd_ns + e.bwd_ns) / (double)grand,
                  (long long)e.elems);
    out += line;
  }
  std::snprintf(line, sizeof line, "%-22s %10s %12lld ns total\\n", "", "",
                (long long)grand);
  out += line;
  return out;
}
"""
new_report = """  std::ostringstream out;
  out << std::left << std::setw(22) << "opcode" << ' ' << std::right
      << std::setw(10) << "calls" << ' ' << std::setw(12) << "fwd ns" << ' '
      << std::setw(12) << "bwd ns" << ' ' << std::setw(6) << "%" << ' '
      << std::setw(12) << "elems" << '\\n';
  for (uint16_t op : order) {
    const ProfEntry& e = prof_[op];
    const double pct = 100.0 * (double)(e.fwd_ns + e.bwd_ns) / (double)grand;
    out << std::left << std::setw(22) << opcode_name(op) << ' ' << std::right
        << std::setw(10) << (long long)e.calls << ' ' << std::setw(12)
        << (long long)e.fwd_ns << ' ' << std::setw(12) << (long long)e.bwd_ns
        << ' ' << std::setw(5) << std::fixed << std::setprecision(1) << pct
        << '%' << ' ' << std::setw(12) << (long long)e.elems << '\\n';
  }
  out << std::left << std::setw(22) << "" << ' ' << std::right << std::setw(10)
      << "" << ' ' << std::setw(12) << (long long)grand << " ns total\\n";
  return out.str();
}
"""
assert old_report in text, "profile_report body not found -- executor.cpp changed upstream"
text = text.replace(old_report, new_report, 1)

open(path, "w").write(text)
EOF
