on:
  push:
    branches: cross
  pull_request:
    branches: main

name: R-CMD-check-crossplatform

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    name: Check (${{ matrix.config.platform }})

    strategy:
      fail-fast: false
      matrix:
        config:
          -  { platform: 386 }
          -  { platform: armhf }
          -  { platform: ppc64le }
          -  { platform: s390x }
          -  { platform: riscv64 }
          -  { platform: FreeBSD }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup QEMU
        if: matrix.config.platform != 'FreeBSD'
        uses: docker/setup-qemu-action@master

      - name: Check package
        if: matrix.config.platform != 'FreeBSD'
        uses: addnab/docker-run-action@v3
        with:
          image: debian:sid-slim
          options: -v ${{ github.workspace }}:/stanr --platform=linux/${{ matrix.config.platform }} -e DEBIAN_FRONTEND=noninteractive -e TZ=Etc/UTC -e LANG=en_AU.UTF-8
          run: |
            apt-get update
            apt-get install --no-install-recommends -y clang g++ \
              r-base-core locales pandoc qpdf r-cran-rcmdcheck make \
              libcurl4-openssl-dev
            echo "en_AU.UTF-8 UTF-8" >> /etc/locale.gen
            locale-gen en_AU.UTF-8
            mkdir -p ~/.R
            echo "CC=clang
            CXX=clang++
            CXX11=clang++
            CXX14=clang++
            CXX17=clang++
            CXX20=clang++" > ~/.R/Makevars
            Rscript -e 'install.packages(c("pak"), repos = "https://cloud.r-project.org", Ncpus=4)'
            Rscript -e 'pak::pak(c("R6", "QuickJSR", "posterior", "withr", "testthat", "loo"))'
            Rscript -e 'rcmdcheck::rcmdcheck("/stanr", args = c("--no-manual", "--as-cran"), check_dir = "/stanr/check")'

      - name: Test in FreeBSD
        if: matrix.config.platform == 'FreeBSD'
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y R R-cran-rcmdcheck gmake
            mkdir -p ~/.R
            echo "CC=clang
            CXX=clang++
            CXX11=clang++
            CXX14=clang++
            CXX17=clang++
            CXX20=clang++" > ~/.R/Makevars
            Rscript -e 'install.packages(c("pak"), repos = "https://cloud.r-project.org", Ncpus=4)'
            Rscript -e 'pak::pak(c("R6", "QuickJSR", "posterior", "withr", "testthat", "loo"))'
          run: |
            Rscript -e 'rcmdcheck::rcmdcheck("/root/work/stanr/stanr", args = c("--no-manual", "--as-cran"), check_dir = "/root/work/stanr/stanr/check")'

      - name: Upload check results
        uses: actions/upload-artifact@v7
        with:
          name: arch-${{ matrix.config.platform }}-results
          path: check
